apiVersion: apps/v1
kind: Deployment
metadata:
  name:  apiimg
spec:
  selector:
    matchLabels:
      app: apiimg
  template:
    metadata:
      labels:
        app:  apiimg
    spec:
      containers:
      - name:  apiimg
        resources:
          requests:
            cpu: 30m
            memory: 30Mi
          limits:
            cpu: 60m
            memory: 60Mi
